# ----
# Site

title: Acme docs
baseurl: ""
incremental: true

permalink: /articles/:title

layouts_dir: _layouts
includes_dir: _includes
plugins_dir:
 - _plugins

sass:
  sass_dir: _sass
  style: compressed

category_dir: "/"
category_layout: "/_layouts/archive.html"

markdown: kramdown
excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

autoprefixer:
  browsers:
  - last 2 versions

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-unsanitize

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules/
  - .git/

include: ['.htaccess']